ETAB
1010	01.02.1997	PROD	HLIQ  HWEF    BHPT 10 
--********************--
1037	01.08.1991	PROD	HOIL  HWEF    BHPT 10 -- внутрипластовой переток	1522.4-1533 от 13.02.2009
1037	01.09.2009	INJE	HWAT  HWEF    BHPT 300 
--********************--
1035	01.02.1992	PROD	HLIQ  HWEF    BHPT 10 
--********************--
1041	01.11.1991	PROD	HLIQ  HWEF    BHPT 10 
--********************--
1042	01.12.1991	PROD	HLIQ  HWEF    BHPT 10 
--********************--
5ERM	01.02.1972	PROD	HLIQ  HWEF    BHPT 10 
--********************--
1040	01.08.1991	PROD	HLIQ  HWEF    BHPT 10 
--********************--
1021	01.10.1991	PROD	HLIQ  HWEF    BHPT 10 
--********************--
1020	01.11.1995	PROD	HLIQ  HWEF    BHPT 10 
--********************--
2230	01.09.2000	PROD	HLIQ  HWEF    BHPT 10 
--********************--
2231g	01.07.2000	PROD	HLIQ  HWEF    BHPT 10 
--********************--
1036	01.02.1992	PROD	HLIQ  HWEF    BHPT 10 
1036	01.09.2009	INJE	HWAT  HWEF    BHPT 350 
--********************--
687	01.05.1975	PROD	HLIQ  HWEF    BHPT 10 
1006	01.06.1997	PROD	HLIQ  HWEF    BHPT 10 
--********************--
ENDE
